### ISSUE TITLE
Please Add to Main Dalamud Repo!

### ISSUE THREAD

**Issue by kgetit** [cas-c/WhereAmIAgain#1]
Since Where's Waldo plugin is no longer being maintained (and it was clunky anyways), this plugin fits the bill and more. The integration to where the zone times are makes it very seamless! As the title states, please add your plugin with the main repos when you feel it is in release status (even though it is working currently)! Thank you for creating this!

**Comment by cas-c** [comment]
whoa, that's really nice to hear! ah! i'll have to take a look over there and see how that's done, i do think it would be nice to have it if other people are wanting something like this! :'o

**Comment by cas-c** [comment]
i pr'd a testing version over here! i hope i did it correctly. https://github.com/goatcorp/DalamudPlugins/pull/1924

**Comment by kgetit** [comment]
Awesome. Using it now. Waldo is back FYI. BUT, your plugin gives more details then just the zone. Love it!
