### ISSUE TITLE
[Bug?] Customization issue

### ISSUE THREAD

**Issue by cc12138030** [cas-c/WhereAmIAgain#15]
Hello! This issue is similar to what was request in #4 , and was a feature that was working before the most recent update. For some reason, any characters I add to the outside of the string do not display. 

For example:
{1} | {2}, {3}  -- This works perfectly fine, as intended (Territory | Area, Sub)
< {1} | {2}, {3} >  --  However in this case, the "< >" do no show up (it displays the same as the one above)
{1} <> {2}, {3} -- This also works properly (Territory <> Area, Sub)

I included some pictures in case I didn't really explain it properly.

Again, this only happens when the characters are on the outside. If this is intended or is required due to some programming thing, feel free to ignore all this (I know nothing about how this crap works). Just wanted to bring it up because before the recent update this worked. 

Thanks for the plugin and for all your hard work!

![waia1](https://user-images.githubusercontent.com/43885259/209836818-29751aad-e132-4b50-80f1-c7b2cf45c0a0.png)
![waia2](https://user-images.githubusercontent.com/43885259/209836830-c1085248-d4ca-4d4f-b850-b762aac94f5e.png)

**Comment by reiichi001** [comment]
Symbols on the front and back are not supported and are purposely stripped from the start and end of the string. 

Plugins should not be responsible for adding separators. This should be a request for Dalamud to include in DTRBar handling so it can be applied to any/every plugin without having to hardcode it.
