### ISSUE TITLE
text box config

### ISSUE THREAD

**Issue by faywinne** [cas-c/WhereAmIAgain#17]
For some inputs, some characters are missing from the output in the server bar.
More specifically, characters that are not alphanumeric, are ignored, unless adjacent to an alphanumeric character.

Examples:
--{2}, {1}--
output: The Drowning Wench, Limsa Lominsa Upper Decks

A--{2}, {1}--
output: A-- The Drowning Wench, Limsa Lominsa Upper Decks

A--{2}, {1}--0
output: A-- The Drowning Wench, Limsa Lominsa Upper Decks--0

*also occurs with special characters in the ffxiv space, such as the HQ symbol, or playstation symbols.

![screenshot 1672761295](https://user-images.githubusercontent.com/36473318/210394313-7fb1792c-0596-4df5-b701-45213eae3342.png)
![screenshot 1672761264](https://user-images.githubusercontent.com/36473318/210394317-aa19ee81-8a85-4c8d-b751-ce9a8b143f50.png)
![screenshot 1672761245](https://user-images.githubusercontent.com/36473318/210394318-033a1308-4c5b-48fc-b534-236cf2a4a474.png)

**Comment by MidoriKami** [comment]
Already fixed in #16 hasn't be pushed live yet
