### ISSUE TITLE
At-all possible to add {Instance} for EW locations?

### ISSUE THREAD

**Issue by NadyaNayme** [cas-c/WhereAmIAgain#2]
I know instances go away in time so the usefulness of displaying it may be ephemeral but it would be very nice for FATE trains and Hunts to finally ditch my `/instance` macro. The System message can be very easy to miss, especially on super chatty Hunt trains where a few shouts can push it off-screen immediately.

**Comment by cas-c** [comment]
Ah I would like this as well!! :) I did look at it a little bit but don't have a clear answer on how to do it yet, still in progress!

**Comment by NadyaNayme** [comment]
I've since added this to Tidy Chat as part of improving the `/instance` message. If you'd like to steal it since it still makes sense to have in WAIA. The relevant bits of code are:

```
// The signature that sets the Instance bit - you can safely run it on `OnTerritoryChanged` because if there is not an instance the value is set to 0.
var InstanceSignaturePtr = SigScanner.GetStaticAddressFromSig("48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 80 BD");

 // This will return the instance value: 0,1,2,3. 0 is no instance, 1-3 are instances 1, 2, or 3
int InstanceNumberFromSignature = Marshal.ReadByte(InstanceSignaturePtr, 0x20);

// These are the equivalent to the <1> <2> <3> SeIcons in game. You can use the string as-is. Square's Axis font takes care of the rest and displays the icon properly.
public static readonly string FirstInstance = "";
public static readonly string SecondInstance = "";
public static readonly string ThirdInstance = "";
```

**Comment by cas-c** [comment]
oh this is lovely! ;_; i appreciate this so much @NadyaNayme really nice work with tidychat also.

in general, i should have some time soon for updates.
