### ISSUE TITLE
Area name missing

### ISSUE THREAD

**Issue by Aegarain** [cas-c/WhereAmIAgain#22]
{2}, which should display the Area name, doesn't show any text in the ui. {3} shows what I think is the area name instead of the points of interest

Examples using default config: {0}, {1}, {2}, {3}
Crystarium Aetheryte: Norvrandt, The Crystarium, The Rotunda
Mor Dhona Aetheryte: Mor Dhona, Mor Dhona, Fogfens

Changing the config to {0}, {1}. {3} does not change the ui.

**Comment by MidoriKami** [comment]
Cause is incorrect offsets, https://github.com/aers/FFXIVClientStructs/pull/389

**Comment by MidoriKami** [comment]
Fixed in 168c73336161c13aac54f38931db34f472f8a2e6
