### ISSUE TITLE
Smileton area name truncated

### ISSUE THREAD

**Issue by keysmashes** [cas-c/WhereAmIAgain#23]
There's an area in Smileton called "Under Construction (Sorry!)", which WAIA removes the last two characters of:

![image](https://github.com/cas-c/WhereAmIAgain/assets/9433472/290e77ad-1fcc-4aed-acea-bc508b5843fb)

**Comment by MidoriKami** [comment]
![image](https://github.com/cas-c/WhereAmIAgain/assets/9083275/b4fc43f6-baa8-48cd-b7ab-6489795cb56e)

**Comment by keysmashes** [comment]
fwiw, it now doesn't remove an extraneous separator at the start:

![image](https://github.com/cas-c/WhereAmIAgain/assets/9433472/2d5689e9-febd-452e-9bc0-177bde5d3fe9)

**Comment by MidoriKami** [comment]
~~PR's are accepted, I genuinely don't care enough about a leading separator. 
Caring about leading separators makes the logic 10x more complicated, and frankly I am getting tired of dealing with bullshit string nonsense.~~

I figured out a simple way to do it.

**Comment by keysmashes** [comment]
\o/ thank you :)
