### ISSUE TITLE
Ward not always showing

### ISSUE THREAD

**Issue by drejjmit** [cas-c/WhereAmIAgain#24]
Teleporting from Limsa to your estate and it won't show your ward. 
Teleporting from Mist to LB or vise versa will show ward. 
Swapping ward will show ward. 
So looks like teleporting from something other than another housing area and ward will not be shown.

**Comment by MidoriKami** [comment]
Unable to reproduce. Please include a video recording of the bug occuring.

https://github.com/cas-c/WhereAmIAgain/assets/9083275/9157098d-315c-4b67-b8ba-816bc049c151

**Comment by drejjmit** [comment]
> Please include a video recording of the bug occuring.

https://i.imgur.com/O5dteos.mp4

**Comment by drejjmit** [comment]
> Please include a video recording of the bug occuring.

https://i.imgur.com/pUXXqAX.mp4
