### ISSUE TITLE
Feature Request: Option to append location to the right side instead

### ISSUE THREAD

**Issue by jake770321** [cas-c/WhereAmIAgain#26]
Would it be possible to add an option to have the location added to the right side of server info rather than the left? I hope this isn't too much trouble. Thank you for this amazing plugin! It's very useful as a new player to familiarise myself with the different zones.

**Comment by MidoriKami** [comment]
This is not possible to do from WhereAmIAgain's plugin code, as Dalamud itself is what controls and manages the DTR Bar (Server Info Bar).

There is an option in Dalamud's settings to make all DTR entries grow to the right side of the DTR Bar, but if you are looking for some things to be on one side and other be on the other side, that's not possible at this time.

**Comment by jake770321** [comment]
That accomplishes exactly what i wanted. Thank you!
