### ISSUE TITLE
[Feature request] Chat command

### ISSUE THREAD

**Issue by Reava** [cas-c/WhereAmIAgain#27]
Shot in the dark since this doesn't seem to have received any updates nor needed one somehow in forever but

I'd like a way to toggle the info in the server bar on/off without toggling the plugin and have a chat command for toggling that as well as a chat command for printing current location as formatted for info bar in chat for easy copy/paste.

Bonus idea would be to be able to toggle server bar info state based on active HUD (so for example have 4 checkboxes to signify which HUD layouts it's active in)

Thank you for your work!

**Comment by MidoriKami** [comment]
Rejected after further consideration.
