### ISSUE TITLE
[REQUEST] Add padding and separator options for the different information

### ISSUE THREAD

**Issue by kgetit** [cas-c/WhereAmIAgain#4]
Hiya. I'm back! Love this addon. Hopefully, it will get out of testing stage soon(tm).  :)

If you can add a separator option (i.e. comma, | (divider), *, etc.). Also, padding option between zone types. Thanks again for a great plugin!

**Comment by cas-c** [comment]
oh, neat ideas!!!

and yes i would like to move it out of testing soon, but i'd like to get the location data in a way where it won't matter what language a person's game is in, etc.  but that was a bigger thing to tackle than initially thought 🤔 

the other things should be doable regardless of that though! :D

**Comment by cas-c** [comment]
I added both of those options by way of input field where you can add more spaces if you need just by typing ' '! :)  It's merged into testing now.  Thanks for the suggestion!!
https://github.com/goatcorp/DalamudPlugins/pull/1997
