### ISSUE TITLE
regex fix for Japanese language

### ISSUE THREAD

**Issue by ghost** [cas-c/WhereAmIAgain#8]
There is currently an issue where in Japanese certain unintended texts get displayed as location
![image](https://user-images.githubusercontent.com/103216512/182663326-bb6ec966-a4f8-43ca-b5d9-974943cefa7f.png)
(it says "switched to gearset 19 SCH, new gridania" in JP)
![image](https://user-images.githubusercontent.com/103216512/182663395-cd37d7a4-595c-4b19-9add-c2d505b7ec7c.png)
("switched to gearset 19 SCH" is the example given for place name)

I changed the regex to `"[.!。！\]:{RightArrow}]|した$"` and have been testing it for a few days, and it seems this fixes the issue.
。 and ！ are sufficient for filtering 99% of system messages that aren't location.
した$ gets the rest of the strings that for some reason don't have punctuation but aren't location names.

**Comment by cas-c** [comment]
oh!! makes sense. :D thank you for testing it out too!! <3

**Comment by ghost** [comment]
I forgot another common punctuation "…" that I don't think is in any location name
So I edited it to be `[.!。…！\]:{RightArrow}]|した$` and now it's catching those strings as well.

edit: currently using `[.!。…！\]:{RightArrow}]|した$|\d[秒分時]` to also catch the "15 seconds until arena is sealed" string and other countdowns

**Comment by MidoriKami** [comment]
@reiichi001 Can close this issue now, since the new system doesn't interface with toasts, so it doesn't need to be filtered.

**Comment by cas-c** [comment]
Fixed by @MidoriKami's recent rewrite :)
